{
 "title": "APF-Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "etcd_type",
    "query": {
     "query": "label_values(etcd_request_duration_seconds_count, type)"
    }
   },
   {
    "name": "etcd_operation",
    "query": {
     "query": "label_values(etcd_request_duration_seconds_count, operation)"
    }
   },
   {
    "name": "verb",
    "query": {
     "query": "label_values(apiserver_request_duration_seconds_count, verb)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(apiserver_request_duration_seconds_count, resource)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "P&F metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests waiting time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_wait_duration_seconds_bucket[1m]))  by (le, priority_level))",
       "legendFormat": "{{priority_level}}"
      }
     ]
    },
    {
     "title": "Execution time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_flowcontrol_request_execution_seconds_bucket[1m]))  by (le, priority_level))",
       "legendFormat": "{{priority_level}}"
      }
     ]
    },
    {
     "title": "Total execution time per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(apiserver_flowcontrol_request_execution_seconds_sum[1m]))  by (priority_level)",
       "legendFormat": "{{priority_level}}"
      }
     ]
    },
    {
     "title": "Requests rate by priority level",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(apiserver_flowcontrol_dispatched_requests_total[1m])) by (priority_level)",
       "legendFormat": "{{priority_level}}"
      }
     ]
    },
    {
     "title": "Dispatched requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_flowcontrol_dispatched_requests_total[1m])) by (priority_level)",
       "legendFormat": "{{priority_level}} {{flow_schema}}"
      }
     ]
    },
    {
     "title": "Current executing requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_flowcontrol_current_executing_requests) by (priority_level)",
       "legendFormat": "{{priority_level}}"
      }
     ]
    },
    {
     "title": "Inqueue requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_flowcontrol_current_inqueue_requests) by (priority_level)",
       "legendFormat": "{{priority_level}} {{flow_schema}}"
      }
     ]
    },
    {
     "title": "Rejected requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(apiserver_flowcontrol_rejected_requests_total[1m])",
       "legendFormat": "{{priority_level}} {{flow_schema}}"
      }
     ]
    },
    {
     "title": "Concurrency in use",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_flowcontrol_request_concurrency_in_use) by (priority_level)",
       "legendFormat": "{{priority_level}}"
      }
     ]
    },
    {
     "title": "Concurrency limits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(apiserver_flowcontrol_request_concurrency_limit) by (priority_level)",
       "legendFormat": "{{priority_level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "kube-apiserver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=\"master\", endpoint=\"apiserver\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "gc rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_count{job=\"master\", endpoint=\"apiserver\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "alloc rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"master\", endpoint=\"apiserver\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number of active watches",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_registered_watchers{kind=~\"(?i:(${resource:regex}))s*\"}) by (instance, group, version, kind)",
       "legendFormat": "{{instance}}: {{version}}.{{group}}.{{kind}}"
      }
     ]
    },
    {
     "title": "Watch events rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(apiserver_watch_events_total{kind=~\"(?i:(${resource:regex}))s*\"}[1m])) by (instance, group, version, kind)",
       "legendFormat": "{{instance}}: {{version}}.{{group}}.{{kind}}"
      }
     ]
    },
    {
     "title": "Watch events traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(apiserver_watch_events_sizes_sum{kind=~\"(?i:(${resource:regex}))s*\"}[1m])) by (instance, group, version, kind)",
       "legendFormat": "{{instance}}: {{version}}.{{group}}.{{kind}}"
      }
     ]
    },
    {
     "title": "Watch event avg size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_watch_events_sizes_sum{kind=~\"(?i:(${resource:regex}))s*\"}[1m])/rate(apiserver_watch_events_sizes_count{kind=~\"(?i:(${resource:regex}))s*\"}[1m])) by (instance, group, version, kind)",
       "legendFormat": "{{instance}}: {{version}}.{{group}}.{{kind}}"
      }
     ]
    },
    {
     "title": "Watch terminated total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_terminated_watchers_total{}[1m])) by (resource, instance)",
       "legendFormat": "{{instance}}: {{resource}}"
      }
     ]
    },
    {
     "title": "Inflight requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_current_inflight_requests) by (requestKind, instance)",
       "legendFormat": "{{instance}}: {{requestKind}}"
      }
     ]
    },
    {
     "title": "Request rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{verb=~\"${verb:regex}\", resource=~\"${resource:regex}s*\"}[1m])) by (verb, resource, subresource, instance)"
      }
     ]
    },
    {
     "title": "Request rate by code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total[1m])) by (code, instance)",
       "legendFormat": "{{instance}}: {{code}}"
      }
     ]
    },
    {
     "title": "Request latency (50th percentile) (excl. WATCH)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "apiserver:apiserver_request_latency:histogram_quantile{quantile=\"0.50\", verb!=\"WATCH\", verb=~\"${verb:regex}\", resource=~\"${resource:regex}s*\"}"
      }
     ]
    },
    {
     "title": "Request latency (99th percentile) (excl. WATCH)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "apiserver:apiserver_request_latency:histogram_quantile{quantile=\"0.99\", verb!=\"WATCH\", verb=~\"${verb:regex}\", resource=~\"${resource:regex}s*\"}"
      }
     ]
    },
    {
     "title": "Traffic (excl. WATCH)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_response_sizes_sum{verb!=\"WATCH\", verb=~\"${verb:regex}\", resource=~\"${resource:regex}s*\"}[1m])) by (verb, version, resource, subresource, scope, instance)"
      }
     ]
    },
    {
     "title": "Webhook admission duration (99th percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_admission_webhook_admission_duration_seconds_bucket[1m])) by (le, type, name))",
       "legendFormat": "{{type}}: {{name}}"
      }
     ]
    },
    {
     "title": "Request filter latency for each filter type (99th percentile)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_filter_duration_seconds_bucket[1m])) by (le, filter))",
       "legendFormat": "{{filter}}"
      }
     ]
    }
   ]
  }
 ]
}