AWSTemplateFormatVersion: "2010-09-09"
Description: Resources used by https://github.com/awslabs/kit/operator
Resources:
  CertificateControllerRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CertificateControllerRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                !Sub "ec2.${AWS::URLSuffix}"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSClusterPolicy"
