#!/bin/bash

set -e

VERSION=KIT_VERSION
GOARCH="amd64"
GOOS="darwin"
echo "Version is $VERSION"
rm -rf bin

ZIPFILENAME=kitcli_v${VERSION}_${GOOS}_${GOARCH}.zip
zip bin/${ZIPFILENAME} -j bin/kitcli

cat << EOF > kitcli.rb
# This file was generated by release.sh
require 'formula'
class Kitcli < Formula
  homepage 'https://github.com/awslabs/kubernetes-iteration-toolkit/substrate'
  version ${VERSION}
  if Hardware::CPU.is_64_bit?
    url 'https://github.com/awslabs/kubernetes-iteration-toolkit/releases/download/v${VERSION}/${ZIPFILENAME}'
    sha256 '$( sha256sum bin/${ZIPFILENAME}  | awk '{ print $1 }' | xargs printf )'
  else
    echo "Hardware not supported"
    exit 1
  end
  def install
    bin.install 'kitcli'
  end
end
EOF
