name: Build CLI binary
on:
  push:
    branches-ignore: [main]
  workflow_dispatch: {}
jobs:
  build:
    strategy:
      matrix:
        os: ["darwin"]
        arch: ["amd64"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "GOOS=darwin" >> $GITHUB_ENV
        echo "GOARCH=amd64" >> $GITHUB_ENV
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.1'
    - name: Build the KIT CLI
      run: |
        go build -o kitcli ./cmd/
      working-directory: substrate